DROP TABLE IF EXISTS bill_events CASCADE;
DROP TABLE IF EXISTS bills CASCADE;
DROP TABLE IF EXISTS collection_run_brands CASCADE;
DROP TABLE IF EXISTS price_snapshots CASCADE;
DROP TABLE IF EXISTS collection_runs CASCADE;
DROP TABLE IF EXISTS product_variants CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
